# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 4, 24, 20, 50749)),
        ),
    ]
